FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Chỉ copy các project cần thiết
COPY NamEcommerce/Domain/ Domain/
COPY NamEcommerce/Application/ Application/
COPY NamEcommerce/Infrastructure/NamEcommerce.Data/ Infrastructure/NamEcommerce.Data/
COPY NamEcommerce/Infrastructure/NamEcommerce.Data.SqlServer/ Infrastructure/NamEcommerce.Data.SqlServer/
COPY NamEcommerce/Presentation/Customer/ Presentation/Customer/

RUN dotnet publish Presentation/Customer/NamEcommerce.Customer.Api/NamEcommerce.Customer.Api.csproj \
    -c Release \
    -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*
ENV TZ=Asia/Ho_Chi_Minh

COPY --from=build /app/publish .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "NamEcommerce.Customer.Api.dll"]
