FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Chỉ copy các project cần thiết
COPY NamEcommerce/Domain/ Domain/
COPY NamEcommerce/Application/ Application/
COPY NamEcommerce/Infrastructure/NamEcommerce.Data/ Infrastructure/NamEcommerce.Data/
COPY NamEcommerce/Infrastructure/NamEcommerce.Data.SqlServer/ Infrastructure/NamEcommerce.Data.SqlServer/
COPY NamEcommerce/Presentation/NamEcommerce.Web/ Presentation/NamEcommerce.Web/
COPY NamEcommerce/Presentation/NamEcommerce.Web.Contracts/ Presentation/NamEcommerce.Web.Contracts/
COPY NamEcommerce/Presentation/NamEcommerce.Web.Framework/ Presentation/NamEcommerce.Web.Framework/

RUN dotnet publish Presentation/NamEcommerce.Web/NamEcommerce.Web.csproj \
    -c Release \
    -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app

RUN apt-get update && apt-get install -y tzdata && rm -rf /var/lib/apt/lists/*
ENV TZ=Asia/Ho_Chi_Minh

COPY --from=build /app/publish .
RUN mkdir -p /app/wwwroot/uploads

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Production

ENTRYPOINT ["dotnet", "NamEcommerce.Web.dll"]
