global using Xunit;
global using Moq;
global using NamEcommerce.Domain.Services;
global using NamEcommerce.Domain.Entities.Catalog;
global using NamEcommerce.Domain.Shared.Exceptions.Catalog;
global using NamEcommerce.Domain.Shared.Dtos.Catalog;
global using NamEcommerce.Data.Contracts;
global using NamEcommerce.TestHelper;
global using NamEcommerce.Domain.Test.Helpers;
