
DELETE FROM tbl.CustomerDebt
DELETE FROM tbl.CustomerPayment
DELETE FROM tbl.CustomerRefund
DELETE FROM tbl.CustomerReturn
DELETE FROM tbl.DeliveryNote
DELETE FROM tbl.DirectShipAddressChangeLog
DELETE FROM tbl.Expenses
DELETE FROM tbl.GoodsReceipt
DELETE FROM tbl.InventoryStock
DELETE FROM tbl.ProductReservationLedger
DELETE FROM tbl.PurchaseOrderItemAllocation
DELETE FROM tbl.OrderItemChangeAudit
DELETE FROM tbl.[Order]
DELETE FROM tbl.OutboxMessage
DELETE FROM tbl.ProductPriceHistory
DELETE FROM tbl.PurchaseOrderItemChangeAudit
DELETE FROM tbl.PurchaseOrder
DELETE FROM tbl.StockAdjustmentNote
DELETE FROM tbl.StockAuditLog
DELETE FROM tbl.StockMovementLog
DELETE FROM tbl.VendorDebt
DELETE FROM tbl.VendorPayment
DELETE FROM tbl.VendorReturn
DELETE FROM tbl.InventoryCostAllocation
DELETE FROM tbl.InventoryCostLayer
DELETE FROM tbl.InventoryCostLedgerEntry
DELETE FROM tbl.CustomerSecurityEvent
DELETE FROM tbl.[CustomerReturnRequest]
DELETE FROM tbl.CustomerCreditNote
DELETE FROM tbl.VendorCreditNote
DELETE FROM tbl.CustomerLedgerEntry
DELETE FROM tbl.VendorLedgerEntry
DELETE FROM tbl.CustomerAccountBalance
DELETE FROM tbl.VendorAccountBalance
DELETE FROM tbl.DeliveryRun
DELETE FROM tbl.[OrderFulfillmentSchedule]
DELETE FROM tbl.FixedAsset