global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using NamEcommerce.Data.Contracts;
global using NamEcommerce.Domain.Shared;
global using NamEcommerce.Domain.Entities.Catalog;
global using NamEcommerce.Domain.Entities.Users;
global using NamEcommerce.Domain.Entities.Security;
global using NamEcommerce.Domain.Entities.Media;
global using NamEcommerce.Domain.Entities.Orders;
global using static NamEcommerce.Data.SqlServer.NamEcommerceDataDefaults;
